// Copyright 2013 The Closure Library Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview List formatting symbols for all locales.
 *
 * This file is autogenerated by script.  See
 * http://go/generate_list_symbols.py using --for_closure
 * File generated from CLDR ver. 25
 *
 * To reduce the file size (which may cause issues in some JS
 * developing environments), this file will only contain locales
 * that are usually supported by Google products. It is a super
 * set of 40 languages. The rest of the data can be found in another file
 * named "listsymbolsext.js", which will be generated at the same
 * time as this file.
 * Before checkin, this file could have been manually edited. This is
 * to incorporate changes before we could correct CLDR. All manual
 * modification must be documented in this section, and should be
 * removed after those changes land to CLDR.
 */

goog.provide('goog.labs.i18n.ListFormatSymbols');
goog.provide('goog.labs.i18n.ListFormatSymbols_en_US');
goog.provide('goog.labs.i18n.ListFormatSymbols_ja_JP');
goog.provide('goog.labs.i18n.ListFormatSymbols_zh_CN');


/**
 * List formatting symbols for locale en_US.
 */
goog.labs.i18n.ListFormatSymbols_en_US = {
  GENDER_STYLE: 0,
  LIST_TWO: '{0} and {1}',
  LIST_START: '{0}, {1}',
  LIST_MIDDLE: '{0}, {1}',
  LIST_END: '{0}, and {1}'
};


/**
 * List formatting symbols for locale ja_JP.
 */
goog.labs.i18n.ListFormatSymbols_ja_JP = {
  GENDER_STYLE: 0,
  LIST_TWO: '{0}、{1}',
  LIST_START: '{0}、{1}',
  LIST_MIDDLE: '{0}、{1}',
  LIST_END: '{0}、{1}'
};


/**
 * List formatting symbols for locale zh_CN.
 */
goog.labs.i18n.ListFormatSymbols_zh_CN = {
  GENDER_STYLE: 2,
  LIST_TWO: '{0}和{1}',
  LIST_START: '{0}、{1}',
  LIST_MIDDLE: '{0}、{1}',
  LIST_END: '{0}和{1}'
};


/**
 * Default value, in case nothing else matches
 */
goog.labs.i18n.ListFormatSymbols = goog.labs.i18n.ListFormatSymbols_en_US;


/**
 * Selecting symbols by locale.
 */
if (goog.LOCALE == 'ja') {
  goog.labs.i18n.ListFormatSymbols = goog.labs.i18n.ListFormatSymbols_ja_JP;
}

if (goog.LOCALE == 'ja_JP' || goog.LOCALE == 'ja-JP') {
  goog.labs.i18n.ListFormatSymbols = goog.labs.i18n.ListFormatSymbols_ja_JP;
}

if (goog.LOCALE == 'zh') {
  goog.labs.i18n.ListFormatSymbols = goog.labs.i18n.ListFormatSymbols_zh_CN;
}

if (goog.LOCALE == 'zh_CN' || goog.LOCALE == 'zh-CN') {
  goog.labs.i18n.ListFormatSymbols = goog.labs.i18n.ListFormatSymbols_zh_CN;
}
